"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, FilePlus2, Gauge, Search, Wallet, X } from "lucide-react";
import Link from "next/link";

export type MonthlyRoomItem = { roomId: string; roomNumber: string; tenantName: string; meterDone: boolean; invoiceId: string | null; invoiceNumber: string | null; invoiceTotal: number; paidAmount: number; balance: number; status: "missing_meter" | "ready_invoice" | "unpaid" | "complete" };
const statusInfo = { missing_meter: { label: "ยังไม่จดมิเตอร์", style: "bg-rose-50 text-rose-700", href: "/meters", action: "จดมิเตอร์", Icon: Gauge }, ready_invoice: { label: "พร้อมออกบิล", style: "bg-amber-50 text-amber-700", href: "/invoices", action: "ออกบิล", Icon: FilePlus2 }, unpaid: { label: "รอรับชำระ", style: "bg-blue-50 text-blue-700", href: "/payments", action: "รับชำระ", Icon: Wallet }, complete: { label: "เสร็จครบ", style: "bg-teal-50 text-teal-700", href: "/invoices", action: "ดูบิล", Icon: CheckCircle2 } } as const;
const money = (value: number) => `฿${value.toLocaleString("th-TH", { maximumFractionDigits: 2 })}`;

export function MonthlyRoomList({ rooms }: { rooms: MonthlyRoomItem[] }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const filtered = useMemo(() => rooms.filter((room) => `${room.roomNumber} ${room.tenantName}`.toLowerCase().includes(query.toLowerCase()) && (status === "all" || room.status === status)), [rooms, query, status]);
  const active = Boolean(query || status !== "all");
  const reset = () => { setQuery(""); setStatus("all"); };
  return <section className="mt-6 overflow-hidden rounded-2xl bg-white"><div className="border-b p-5"><h2 className="font-bold">สถานะแต่ละห้อง</h2><p className="mt-1 text-xs text-slate-500">แสดง {filtered.length} จาก {rooms.length} ห้องที่มีสัญญาในรอบเดือนนี้</p></div><div className="grid gap-3 border-b p-4 sm:grid-cols-[1fr_190px_auto]"><label className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาห้องหรือชื่อผู้เช่า" className="w-full rounded-xl border py-2.5 pl-9 pr-3 text-sm"/></label><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="all">ทุกสถานะ</option><option value="missing_meter">ยังไม่จดมิเตอร์</option><option value="ready_invoice">พร้อมออกบิล</option><option value="unpaid">รอรับชำระ</option><option value="complete">เสร็จครบ</option></select>{active ? <button onClick={reset} className="inline-flex items-center justify-center gap-1 rounded-xl border px-3 py-2 text-sm text-slate-600"><X size={15}/>ล้าง</button> : <span/>}</div>
    {!filtered.length ? <div className="p-12 text-center text-sm text-slate-500">ไม่พบห้องตามเงื่อนไขที่เลือก</div> : <><div className="grid gap-3 p-4 lg:hidden">{filtered.map((room) => { const info = statusInfo[room.status]; return <article key={room.roomId} className="rounded-2xl border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">ห้อง {room.roomNumber}</h3><p className="text-sm text-slate-500">{room.tenantName}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${info.style}`}>{info.label}</span></div><div className="mt-4 grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3 text-center text-xs"><div><p className="text-slate-500">มิเตอร์</p><b>{room.meterDone ? "ครบ" : "ยังไม่ครบ"}</b></div><div><p className="text-slate-500">ยอดบิล</p><b>{room.invoiceId ? money(room.invoiceTotal) : "-"}</b></div><div><p className="text-slate-500">คงเหลือ</p><b>{room.invoiceId ? money(room.balance) : "-"}</b></div></div><Link href={room.invoiceId && room.status === "complete" ? `/invoices/${room.invoiceId}` : info.href} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-teal-200 px-3 py-2 text-sm font-medium text-teal-700"><info.Icon size={15}/>{info.action}</Link></article>; })}</div><div className="hidden overflow-x-auto lg:block"><table className="min-w-full text-left text-sm"><thead><tr><th className="px-5 py-3">ห้อง / ผู้เช่า</th><th className="px-5 py-3">มิเตอร์</th><th className="px-5 py-3">ใบแจ้งหนี้</th><th className="px-5 py-3 text-right">ยอดบิล</th><th className="px-5 py-3 text-right">รับแล้ว</th><th className="px-5 py-3 text-right">คงเหลือ</th><th className="px-5 py-3">สถานะ</th><th className="px-5 py-3"></th></tr></thead><tbody>{filtered.map((room) => { const info = statusInfo[room.status]; return <tr key={room.roomId} className="border-t"><td className="px-5 py-4"><b>ห้อง {room.roomNumber}</b><small className="block text-slate-500">{room.tenantName}</small></td><td className="px-5 py-4">{room.meterDone ? <span className="text-teal-700">✓ จดแล้ว</span> : <span className="text-rose-700">ยังไม่จด</span>}</td><td className="px-5 py-4">{room.invoiceNumber || "-"}</td><td className="px-5 py-4 text-right font-medium">{room.invoiceId ? money(room.invoiceTotal) : "-"}</td><td className="px-5 py-4 text-right text-teal-700">{room.invoiceId ? money(room.paidAmount) : "-"}</td><td className="px-5 py-4 text-right font-bold text-amber-800">{room.invoiceId ? money(room.balance) : "-"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${info.style}`}>{info.label}</span></td><td className="px-5 py-4"><Link href={room.invoiceId && room.status === "complete" ? `/invoices/${room.invoiceId}` : info.href} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs font-medium text-teal-700"><info.Icon size={14}/>{info.action}</Link></td></tr>; })}</tbody></table></div></>}
  </section>;
}
