import {AlertTriangle,ArrowLeft,Banknote,CalendarDays,Droplets,FileText,Gauge,Home,ReceiptText,UserRound,Wallet,Wrench,Zap} from "lucide-react";
import Link from "next/link";
import {notFound,redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {RoomActions} from "../room-actions";

const money=(value:number)=>`฿${value.toLocaleString("th-TH",{maximumFractionDigits:2})}`;
const showDate=(value?:string|null)=>value?new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"numeric"}):"-";
const showMonth=(value:string)=>new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString("th-TH",{month:"long",year:"numeric"});
const relation=(value:any)=>Array.isArray(value)?value[0]??null:value??null;
const invoiceLabels:Record<string,string>={draft:"ฉบับร่าง",issued:"รอชำระ",paid:"ชำระแล้ว",overdue:"เกินกำหนด",void:"ยกเลิก"};
const maintenanceLabels:Record<string,string>={open:"รอดำเนินการ",in_progress:"กำลังดำเนินการ",completed:"เสร็จแล้ว",cancelled:"ยกเลิก"};

export default async function RoomDetailPage({params}:{params:Promise<{roomId:string}>}){
  const {roomId}=await params;
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user)redirect("/login");
  const [{data:profile},roomResult]=await Promise.all([
    supabase.from("profiles").select("role").eq("id",user.id).maybeSingle(),
    supabase.from("rooms").select("id,room_number,floor,room_type,size_sqm,monthly_rent,deposit,water_rate,electric_rate,status").eq("id",roomId).is("deleted_at",null).maybeSingle(),
  ]);
  if(!profile||!["owner","staff"].includes(profile.role))redirect("/dashboard");
  if(!roomResult.data)notFound();
  const room=roomResult.data;
  const [leasesResult,metersResult,invoicesResult,maintenanceResult,expensesResult]=await Promise.all([
    supabase.from("leases").select("id,start_date,end_date,rent_amount,deposit_amount,active,profiles!leases_tenant_id_fkey(full_name,phone)").eq("room_id",roomId).order("created_at",{ascending:false}),
    supabase.from("meter_readings").select("id,reading_month,water_previous,water_current,electric_previous,electric_current").eq("room_id",roomId).order("reading_month",{ascending:false}).limit(24),
    supabase.from("invoices").select("id,invoice_number,billing_month,due_date,total_amount,status").eq("room_id",roomId).order("billing_month",{ascending:false}).limit(24),
    supabase.from("maintenance_requests").select("id,title,description,status,priority,scheduled_date,created_at").eq("room_id",roomId).order("created_at",{ascending:false}).limit(50),
    supabase.from("expenses").select("id,expense_date,category,description,amount").eq("room_id",roomId).is("deleted_at",null).order("expense_date",{ascending:false}).limit(50),
  ]);
  const leases=leasesResult.data??[],meters=metersResult.data??[],invoices=invoicesResult.data??[],maintenance=maintenanceResult.data??[],expenses=expensesResult.data??[];
  const invoiceIds=invoices.map(item=>item.id);
  const paymentsResult=invoiceIds.length?await supabase.from("payments").select("id,invoice_id,amount,paid_at,method,reference").in("invoice_id",invoiceIds).order("paid_at",{ascending:false}):{data:[],error:null};
  const payments=paymentsResult.data??[];
  const paidByInvoice=new Map<string,number>();
  payments.forEach(item=>paidByInvoice.set(item.invoice_id,(paidByInvoice.get(item.invoice_id)??0)+Number(item.amount)));
  const activeLease:any=leases.find(item=>item.active)??null;
  const tenant=relation(activeLease?.profiles);
  const totalInvoiced=invoices.filter(item=>item.status!=="void").reduce((sum,item)=>sum+Number(item.total_amount),0);
  const totalPaid=payments.reduce((sum,item)=>sum+Number(item.amount),0);
  const outstanding=invoices.filter(item=>item.status!=="void").reduce((sum,item)=>sum+Math.max(0,Number(item.total_amount)-(paidByInvoice.get(item.id)??0)),0);
  const openMaintenance=maintenance.filter(item=>!["completed","cancelled"].includes(item.status)).length;
  const status=room.status==="occupied"?{label:"มีผู้เช่า",style:"bg-blue-50 text-blue-700"}:room.status==="maintenance"?{label:"ซ่อมบำรุง",style:"bg-amber-50 text-amber-700"}:{label:"ว่าง",style:"bg-teal-50 text-teal-700"};
  const editable={...room,size_sqm:room.size_sqm===null?null:Number(room.size_sqm),monthly_rent:Number(room.monthly_rent),deposit:Number(room.deposit),water_rate:Number(room.water_rate),electric_rate:Number(room.electric_rate)};
  return <main className="min-h-screen bg-slate-50 pb-16">
    <header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><Link href="/rooms" className="grid h-9 w-9 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><ArrowLeft size={19}/></Link><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-teal-600 text-white"><Home size={20}/></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="text-lg font-bold">ห้อง {room.room_number}</h1><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${status.style}`}>{status.label}</span></div><p className="truncate text-xs text-slate-500">ชั้น {room.floor} · {room.room_type}{room.size_sqm?` · ${room.size_sqm} ตร.ม.`:""}</p></div></div><RoomActions room={editable} canArchive={profile.role==="owner"}/></div></header>
    <section className="mx-auto max-w-7xl px-5 py-7">
      <nav className="sticky top-3 z-20 mb-6 flex gap-2 overflow-x-auto rounded-2xl border bg-white/95 p-2 shadow-sm backdrop-blur">{[["overview","ภาพรวม"],["finance","การเงิน"],["meters","มิเตอร์"],["leases","สัญญา"],["operations","ซ่อมและรายจ่าย"]].map(([id,label])=><a key={id} href={`#${id}`} className="whitespace-nowrap rounded-xl px-4 py-2 text-sm font-medium text-slate-600 hover:bg-teal-50 hover:text-teal-700">{label}</a>)}</nav>
      <section id="overview" className="scroll-mt-24"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<Wallet/>} label="ค่าเช่าต่อเดือน" value={money(Number(room.monthly_rent))}/><Summary icon={<UserRound/>} label="ผู้เช่าปัจจุบัน" value={tenant?.full_name??"ยังไม่มีผู้เช่า"} note={tenant?.phone??"-"}/><Summary icon={<Banknote/>} label="ยอดค้างชำระ" value={money(outstanding)} warning={outstanding>0}/><Summary icon={<Wrench/>} label="งานซ่อมที่ยังไม่เสร็จ" value={String(openMaintenance)} warning={openMaintenance>0}/></div>
        <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">ข้อมูลสำคัญของห้อง</h2><div className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info label="เงินประกัน" value={money(Number(room.deposit))}/><Info label="ขนาดห้อง" value={room.size_sqm?`${room.size_sqm} ตร.ม.`:"ไม่ระบุ"}/><Info label="ค่าน้ำต่อหน่วย" value={money(Number(room.water_rate))}/><Info label="ค่าไฟต่อหน่วย" value={money(Number(room.electric_rate))}/></div></article><article className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">ทางลัด</h2><div className="mt-4 grid grid-cols-2 gap-2"><Quick href="/invoices" label="ออกใบแจ้งหนี้"/><Quick href="/payments" label="รับชำระเงิน"/><Quick href="/meters" label="จดมิเตอร์"/><Quick href="/maintenance" label="เพิ่มงานซ่อม"/></div></article></div>
      </section>
      <section id="finance" className="mt-8 scroll-mt-24"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><ReceiptText size={20} className="text-teal-600"/>การเงินของห้อง</h2><p className="text-sm text-slate-500">ใบแจ้งหนี้และยอดรับชำระย้อนหลัง</p></div><div className="flex gap-5 text-right text-sm"><Info label="ออกบิล" value={money(totalInvoiced)}/><Info label="รับแล้ว" value={money(totalPaid)}/></div></div><div className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead><tr><th className="p-4">ใบแจ้งหนี้</th><th className="p-4">รอบบิล</th><th className="p-4">ยอดรวม</th><th className="p-4">รับแล้ว</th><th className="p-4">คงเหลือ</th><th className="p-4">สถานะ</th></tr></thead><tbody>{invoices.map(item=>{const paid=paidByInvoice.get(item.id)??0,balance=item.status==="void"?0:Math.max(0,Number(item.total_amount)-paid);return <tr key={item.id} className="border-t"><td className="p-4"><Link href={`/invoices/${item.id}`} className="font-semibold text-teal-700">{item.invoice_number}</Link></td><td className="whitespace-nowrap p-4">{showMonth(item.billing_month)}</td><td className="p-4">{money(Number(item.total_amount))}</td><td className="p-4 text-teal-700">{money(paid)}</td><td className="p-4 font-semibold">{money(balance)}</td><td className="p-4">{invoiceLabels[item.status]??item.status}</td></tr>})}</tbody></table><Empty show={!invoices.length} text="ยังไม่มีใบแจ้งหนี้ของห้องนี้"/></div></section>
      <section id="meters" className="mt-8 scroll-mt-24"><Title icon={<Gauge/>} title="ประวัติมิเตอร์" subtitle="แสดงย้อนหลังสูงสุด 24 เดือน"/><div className="mt-3 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead><tr><th className="p-4">เดือน</th><th className="p-4">น้ำ ก่อน → หลัง</th><th className="p-4">หน่วยน้ำ</th><th className="p-4">ไฟ ก่อน → หลัง</th><th className="p-4">หน่วยไฟ</th></tr></thead><tbody>{meters.map(item=><tr key={item.id} className="border-t"><td className="whitespace-nowrap p-4 font-medium">{showMonth(item.reading_month)}</td><td className="p-4"><Droplets size={14} className="mr-1 inline text-blue-600"/>{Number(item.water_previous)} → {Number(item.water_current)}</td><td className="p-4 font-semibold text-blue-700">{Number(item.water_current)-Number(item.water_previous)}</td><td className="p-4"><Zap size={14} className="mr-1 inline text-amber-600"/>{Number(item.electric_previous)} → {Number(item.electric_current)}</td><td className="p-4 font-semibold text-amber-700">{Number(item.electric_current)-Number(item.electric_previous)}</td></tr>)}</tbody></table><Empty show={!meters.length} text="ยังไม่มีประวัติมิเตอร์ของห้องนี้"/></div></section>
      <section id="leases" className="mt-8 scroll-mt-24"><Title icon={<FileText/>} title="ประวัติสัญญาเช่า"/><div className="mt-3 space-y-3">{leases.map((item:any)=>{const person=relation(item.profiles);return <article key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-5 shadow-sm"><div><p className="font-semibold">{person?.full_name??"ไม่ระบุผู้เช่า"}</p><p className="text-xs text-slate-500">{person?.phone??"ไม่มีเบอร์โทร"}</p></div><div className="text-sm"><p className="flex items-center gap-1 text-slate-500"><CalendarDays size={14}/>{showDate(item.start_date)} – {showDate(item.end_date)}</p><p className="mt-1">ค่าเช่า <b>{money(Number(item.rent_amount))}</b> · ประกัน <b>{money(Number(item.deposit_amount))}</b></p></div><span className={`rounded-full px-3 py-1 text-xs ${item.active?"bg-teal-50 text-teal-700":"bg-slate-100 text-slate-600"}`}>{item.active?"ใช้งานอยู่":"สิ้นสุดแล้ว"}</span></article>})}<Empty show={!leases.length} text="ยังไม่มีประวัติสัญญาของห้องนี้"/></div></section>
      <section id="operations" className="mt-8 scroll-mt-24"><Title icon={<Wrench/>} title="งานซ่อมและรายจ่ายของห้อง"/>{expensesResult.error&&<div className="mt-3 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle size={19}/><p>ยังโหลดรายจ่ายแยกตามห้องไม่ได้ กรุณารัน migration 015 หนึ่งครั้ง ข้อมูลส่วนอื่นยังใช้งานได้ตามปกติ</p></div>}<div className="mt-3 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl bg-white p-5 shadow-sm"><SectionHeader title="ประวัติงานซ่อม" href="/maintenance"/><div className="mt-4 space-y-3">{maintenance.map(item=><div key={item.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><b>{item.title}</b><span className="text-xs text-slate-500">{maintenanceLabels[item.status]??item.status}</span></div><p className="mt-1 text-sm text-slate-500">{item.description||"ไม่มีรายละเอียด"}</p><p className="mt-2 text-xs text-slate-400">นัดหมาย {showDate(item.scheduled_date)} · {item.priority===1?"เร่งด่วน":item.priority===2?"ปกติ":"ต่ำ"}</p></div>)}<Empty show={!maintenance.length} text="ยังไม่มีประวัติงานซ่อม"/></div></article><article className="rounded-2xl bg-white p-5 shadow-sm"><SectionHeader title="รายจ่ายที่ผูกกับห้อง" href="/expenses" note={`รวม ${money(expenses.reduce((sum,item)=>sum+Number(item.amount),0))}`}/><div className="mt-4 space-y-3">{expenses.map(item=><div key={item.id} className="flex justify-between gap-3 rounded-xl border p-3"><div><b>{item.category}</b><p className="text-sm text-slate-500">{item.description||"ไม่มีรายละเอียด"}</p><p className="mt-1 text-xs text-slate-400">{showDate(item.expense_date)}</p></div><b className="text-rose-700">{money(Number(item.amount))}</b></div>)}<Empty show={!expenses.length&&!expensesResult.error} text="ยังไม่มีรายจ่ายที่ผูกกับห้องนี้"/></div></article></div></section>
      {(leasesResult.error||metersResult.error||invoicesResult.error||maintenanceResult.error||paymentsResult.error)&&<div className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">ข้อมูลบางส่วนโหลดไม่สำเร็จ กรุณาลองรีเฟรชอีกครั้ง</div>}
    </section></main>;
}

function Summary({icon,label,value,note,warning=false}:{icon:React.ReactNode;label:string;value:string;note?:string;warning?:boolean}){return <article className={`rounded-2xl p-5 shadow-sm ${warning?"bg-amber-50":"bg-white"}`}><span className={warning?"text-amber-600":"text-teal-600"}>{icon}</span><p className="mt-3 text-sm text-slate-500">{label}</p><p className="mt-1 truncate text-xl font-bold">{value}</p>{note&&<p className="text-xs text-slate-500">{note}</p>}</article>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-slate-500">{label}</p><b>{value}</b></div>}
function Quick({href,label}:{href:string;label:string}){return <Link href={href} className="rounded-xl bg-teal-50 p-3 text-sm font-medium text-teal-700 hover:bg-teal-100">{label}</Link>}
function Title({icon,title,subtitle}:{icon:React.ReactNode;title:string;subtitle?:string}){return <div><h2 className="flex items-center gap-2 text-lg font-bold"><span className="text-teal-600">{icon}</span>{title}</h2>{subtitle&&<p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</div>}
function Empty({show,text}:{show:boolean;text:string}){return show?<p className="p-8 text-center text-sm text-slate-500">{text}</p>:null}
function SectionHeader({title,href,note}:{title:string;href:string;note?:string}){return <div className="flex items-center justify-between"><div><h3 className="font-bold">{title}</h3>{note&&<p className="text-xs text-slate-500">{note}</p>}</div><Link href={href} className="text-sm font-medium text-teal-700">จัดการ</Link></div>}
