"use client";

import { useActionState, useTransition } from "react";
import { Bell, Link2, Power, Unlink } from "lucide-react";
import { createAdditionalLineLinkCode, disconnectLineConnection, setLineConnectionEnabled, type LineAdminActionState } from "./line-admin-actions-v2";

type Connection = { id: string; profile_id: string; line_user_id: string | null; enabled: boolean; linked_at: string | null; profiles: { full_name: string } | null };

export function LineAdminManagerV2({ connections, currentProfileId }: { connections: Connection[]; currentProfileId: string }) {
  const [state, createCode, pending] = useActionState<LineAdminActionState, FormData>(createAdditionalLineLinkCode, {});
  const [switching, startTransition] = useTransition();
  const disconnect = (id: string) => { if (window.confirm("ยืนยันยกเลิกการเชื่อมต่อ LINE นี้?")) startTransition(() => { void disconnectLineConnection(id); }); };
  return <section className="mt-5 rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 font-bold"><Bell size={18} className="text-teal-600"/>ผู้ดูแล LINE</h2><p className="mt-1 text-sm text-slate-500">เพิ่ม LINE ได้หลายบัญชี แต่ละบัญชีเปิด/ปิดการแจ้งเตือนได้แยกกัน</p></div><form action={createCode}><button disabled={pending} className="inline-flex items-center gap-2 rounded-lg bg-teal-600 px-3 py-2 text-sm font-semibold text-white disabled:bg-teal-400"><Link2 size={16}/>{pending ? "กำลังสร้าง..." : "เพิ่ม LINE บัญชีใหม่"}</button></form></div>{state.code && <div className="mt-4 rounded-xl bg-teal-50 p-4 text-sm text-teal-950"><p>ส่งข้อความนี้ในแชต OA ภายใน 10 นาที:</p><code className="mt-2 inline-block rounded bg-white px-3 py-2 font-semibold">เชื่อม {state.code}</code></div>}{state.error && <p className="mt-3 text-sm text-rose-700">{state.error}</p>}<div className="mt-5 space-y-3">{connections.map((connection, index) => { const own = connection.profile_id === currentProfileId; return <div key={connection.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="font-semibold">{connection.profiles?.full_name ?? "ผู้ดูแล"}{own && <span className="ml-2 text-xs font-normal text-slate-500">(คุณ)</span>} <span className="text-xs font-normal text-slate-400">#{index + 1}</span></p><p className="mt-1 text-sm text-slate-500">{connection.line_user_id ? connection.enabled ? "เชื่อมแล้ว · รับการแจ้งเตือน" : "เชื่อมแล้ว · ปิดการแจ้งเตือน" : "รอเชื่อม LINE"}</p></div>{own && connection.line_user_id && <div className="flex items-center gap-2"><button disabled={switching} onClick={() => startTransition(() => { void setLineConnectionEnabled(connection.id, !connection.enabled); })} className={`inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-semibold ${connection.enabled ? "bg-teal-100 text-teal-800" : "bg-slate-100 text-slate-600"}`}><Power size={14}/>{connection.enabled ? "เปิดอยู่" : "ปิดอยู่"}</button><button disabled={switching} onClick={() => disconnect(connection.id)} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700"><Unlink size={14}/>ยกเลิก</button></div>}</div>; })}{!connections.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">ยังไม่มีผู้ดูแลเชื่อม LINE</p>}</div></section>;
}
