"use client";

import { useActionState } from "react";
import { ChevronDown, Plus } from "lucide-react";
import { createRoom, type RoomFormState } from "./actions";

const initialState: RoomFormState = {};
const field = "mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm";

export function RoomForm({ canManage, waterRate, electricRate, defaultFloor, defaultRoomType }: { canManage: boolean; waterRate: number; electricRate: number; defaultFloor: number; defaultRoomType: "ห้องพัดลม" | "ห้องแอร์" }) {
  const [state, action, pending] = useActionState(createRoom, initialState);
  if (!canManage) return null;
  return <details className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between px-5 py-4"><span className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-teal-50 text-teal-700"><Plus size={18}/></span><span><b className="block">เพิ่มห้องพัก</b><small className="text-slate-500">เปิดแบบฟอร์มเพื่อเพิ่มห้องใหม่</small></span></span><ChevronDown size={18} className="text-slate-400 transition group-open:rotate-180"/></summary><form action={action} className="grid gap-4 border-t border-slate-100 p-5 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium">เลขห้อง<input name="roomNumber" required className={field} placeholder="เช่น 101"/></label><label className="text-sm font-medium">ชั้น<select name="floor" required defaultValue={String(defaultFloor)} className={field}><option value="1">ชั้น 1</option><option value="2">ชั้น 2</option><option value="3">ชั้น 3</option><option value="4">ชั้น 4</option></select></label><label className="text-sm font-medium">ประเภทห้อง<select name="roomType" required defaultValue={defaultRoomType} className={field}><option value="ห้องพัดลม">ห้องพัดลม</option><option value="ห้องแอร์">ห้องแอร์</option></select></label><label className="text-sm font-medium">ค่าเช่าต่อเดือน<input name="monthlyRent" type="number" min="0" required className={field} placeholder="3500"/></label><label className="text-sm font-medium">เงินประกัน<input name="deposit" type="number" min="0" defaultValue="0" className={field}/></label><label className="text-sm font-medium">ขนาดห้อง (ตร.ม.)<input name="sizeSqm" type="number" min="0" step="0.01" className={field} placeholder="24"/></label><label className="text-sm font-medium">ค่าน้ำต่อหน่วย<input name="waterRate" type="number" min="0" step="0.01" defaultValue={waterRate} className={field}/></label><label className="text-sm font-medium">ค่าไฟต่อหน่วย<input name="electricRate" type="number" min="0" step="0.01" defaultValue={electricRate} className={field}/></label><div className="rounded-xl bg-slate-50 px-4 py-3 text-xs text-slate-500 sm:col-span-2 lg:col-span-4">ระบบจำชั้น ประเภทห้อง ค่าน้ำ และค่าไฟที่ใช้ล่าสุดไว้เป็นค่าเริ่มต้นสำหรับห้องถัดไป</div><div className="sm:col-span-2 lg:col-span-4">{state.error && <p className="mb-3 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{state.error}</p>}{state.success && <p className="mb-3 rounded-xl bg-teal-50 px-4 py-3 text-sm text-teal-700">{state.success}</p>}<button disabled={pending} className="rounded-xl bg-teal-600 px-5 py-2.5 text-sm font-semibold text-white disabled:bg-teal-400">{pending ? "กำลังบันทึก..." : "บันทึกห้องพัก"}</button></div></form></details>;
}